apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: beconfident-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: business

  source:
    repoURL: https://github.com/eserafini/beconfident-api
    targetRevision: main
    path: k8s

  destination:
    server: https://kubernetes.default.svc
    namespace: beconfident-api

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: beconfident-api
      name: beconfident-api

  revisionHistoryLimit: 10
