# Template para Application de Preview (PR Environments)
# Este arquivo é usado como base pelo GitHub Actions para gerar Applications dinâmicas
#
# Variáveis que serão substituídas pelo CI:
# - PR_NUMBER: Número da PR (ex: 42)
# - IMAGE_TAG: Tag da imagem Docker (ex: pr-42-abc123)
# - TARGET_REVISION: Branch da PR (ex: feature/new-feature)
# - APP_NAME: Nome da aplicação (ex: gitops-test-app)
#
# Arquivo gerado: clusters/prod-us-central1/apps/pr-<PR_NUMBER>-<APP_NAME>.yaml

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pr-11-gitops-test-app
  namespace: argocd
  labels:
    app.kubernetes.io/name: gitops-test-app
    app.kubernetes.io/instance: pr-11
    preview: "true"
    pr-number: "11"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: business

  source:
    repoURL: https://github.com/eserafini/gitops-test-app
    targetRevision: feat/test-ops
    path: k8s/charts/gitops-test-app
    helm:
      valueFiles:
        - values/preview/values.yaml
      parameters:
        # Apenas parâmetros dinâmicos que mudam por PR
        - name: image.tag
          value: pr-11-d312b9a0
        - name: ingress.hosts[0].host
          value: "pr-11.gitops-test-app.136.113.78.99.nip.io"
        - name: ingress.tls[0].secretName
          value: "pr-11-gitops-test-app-tls"
        - name: ingress.tls[0].hosts[0]
          value: "pr-11.gitops-test-app.136.113.78.99.nip.io"

  destination:
    server: https://kubernetes.default.svc
    namespace: pr-11

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      namespace: pr-11
      name: gitops-test-app

  revisionHistoryLimit: 3
